### ISSUE TITLE
Get error in Chinese Simplified

### ISSUE THREAD

**Issue by GitHubWuYi** [mw-experts/rsql#27]
RsqlToSqlConverter.getInstance().convert('(name==*北京*,name_cn==*北京*)');

result:

TypeError: Unknown token at position 8: '北京*,name_cn==*北京*)'
    at Tokenizer.tokenize (/Users/wuyi/git/9cloud/dongfangmeijing/server/node_modules/@mw-experts/rsql/src/tokenizer/tokenizer.ts:42:19)
    at RsqlTokenizer.tokenize (/Users/wuyi/git/9cloud/dongfangmeijing/server/node_modules/@mw-experts/rsql/src/rsql-tokenizer/rsql-tokenizer.ts:26:27)
    at RsqlToSqlConverter.convert (/Users/wuyi/git/9cloud/dongfangmeijing/server/node_modules/@mw-experts/rsql/src/rsql-to-sql-converter/rsql-to-sql-converter.ts:35:59)

**Comment by misticwonder** [comment]
@GitHubWuYi Thank you for this issue. Added support of unicode values.
Available from version `@mw-experts/rsql@1.5.0`
